# Generated by Django 4.2.30 on 2026-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='veg', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/6643/6643359.png'),
        ),
    ]
