# Generated by Django 4.2.30 on 2026-09-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
